Fixes  #1412 with `TestKafkaBroker` behaviour where Consumer Groups weren't being respected
airtai/faststream pull request #1413
Opened 2024-05-01 10:19 UTC by sifex

# Description

This fixes bug #1412 where distribution of messages on a topic does not get distributed to each consumer group when running the `TestKafkaBroker`. 

Fixes #1412

## Other fixes

- It also fixes a small bug in `DOCKER_COMPOSE_PROJECT` project name generation where the users' username field contains a `.` character (which docker believes to be invalid naming).
- Typo fix in `.github/PULL_REQUEST_TEMPLATE.md`

## Type of change

- [x] Bug fix (a non-breaking change that resolves an issue)

## Checklist

- [x] My code adheres to the style guidelines of this project (`scripts/lint.sh` shows no errors)
- [x] I have conducted a self-review of my own code
- [x] I have made the necessary changes to the documentation
- [x] My changes do not generate any new warnings
- [x] I have added tests to validate the effectiveness of my fix or the functionality of my new feature
- [ ] Both new and existing unit tests pass successfully on my local environment by running `scripts/test-cov.sh` **(No. Currently Segfaults on Local M1 MBP, will rely on GHA)**
- [x] I have ensured that static analysis tests are passing by running `scripts/static-anaylysis.sh`
- [x] I have included code examples to illustrate the modifications

2024-05-01 10:35 UTC, sifex commented
Currently facing an issue where the RPC test assumes you can get a response back from a publisher? Not sure why this assumption was made.

```python
@pytest.mark.asyncio()
    async def test_rpc(self, queue: str, rpc_broker: BrokerUsecase):
        @rpc_broker.subscriber(queue)
        async def m(m):  # pragma: no cover
            return "1"
    
        async with rpc_broker:
            await rpc_broker.start()
            r = await rpc_broker.publish("hello", queue, rpc_timeout=3, rpc=True)
    
>       assert r == "1"
E       AssertionError

```

2024-05-02 19:17 UTC, Lancetnik commented
> Currently facing an issue where the RPC test assumes you can get a response back from a publisher? Not sure why this assumption was made.
> 
> ```python
> @pytest.mark.asyncio()
>     async def test_rpc(self, queue: str, rpc_broker: BrokerUsecase):
>         @rpc_broker.subscriber(queue)
>         async def m(m):  # pragma: no cover
>             return "1"
>     
>         async with rpc_broker:
>             await rpc_broker.start()
>             r = await rpc_broker.publish("hello", queue, rpc_timeout=3, rpc=True)
>     
> >       assert r == "1"
> E       AssertionError
> ```
> 
> imo I think publishers by definition can't return anything other than a ReceiveAck / similar response from the message queue – also not sure if I misunderstand the use case for RPC in this context.

RPC in TestClient allows you to validate your handler result without special publisher creation. I think, we should save this behavior. In you case, if user has the only last result - it should be OK for most cases: (the following pseudocode represents assuming bahavior)

```python
result = None
for sub in subscribers:
    result = call_subscriber(...)
return result
```

2024-05-02 19:29 UTC, Lancetnik commented on faststream/kafka/testing.py
> +            {sub.group_id for sub in self.broker._subscribers.values()}
I don't like O(n**2) in this case. Can we find any decision without iteration throw all subscribers twice?

2024-05-16 21:01 UTC, Lancetnik requested changes
Can you please fix the comments and upload main changes to make it mergeable?

2024-05-18 22:03 UTC, sifex commented
Should be good to go, applied ruff formatting + linting.

2024-05-19 06:33 UTC, Lancetnik commented
I'll check it and solve conflicts with main soon. Thank you for the work!

2024-05-20 17:23 UTC, Lancetnik submitted a review, later dismissed

2024-05-20 17:39 UTC, Lancetnik requested changes
@sifex looks really great, but I now can't understand, why it respects consumer group😆 

Anyway, can you, please add test for this behavior for `publish_batch` method? Then we can merge it

2024-05-25 16:07 UTC, Lancetnik approved these changes

2024-05-25 20:13 UTC, merged