feature/exception_middleware add exception middleware
airtai/faststream pull request #1604
Opened 2024-07-18 12:12 UTC by Rusich90

fixes #1576

Draft: Need create test and check linters

You can use ExceptionMiddleware like examples in issue

```python
from pydantic import ValidationError

from faststream.broker.middlewares.exception import ExceptionMiddleware
from faststream.kafka import KafkaBroker

exception_middleware = ExceptionMiddleware()

@exception_middleware.add_handler(ZeroDivisionError)
async def handle_type_exception(exc: ZeroDivisionError): ...

@exception_middleware.add_handler(ValidationError)
async def handle_validation_error(exc: ValidationError): ...

broker = KafkaBroker("localhost:29092", middlewares=[exception_middleware])

```

or like this

```python
from pydantic import ValidationError

from faststream.broker.middlewares.exception import ExceptionMiddleware
from faststream.kafka import KafkaBroker

async def handle_type_exception(exc: ZeroDivisionError): ...

async def handle_validation_error(exc: ValidationError): ...

exception_handlers = {
    ZeroDivisionError: handle_type_exception,
    ValidationError: handle_validation_error,
}

exception_middleware = ExceptionMiddleware(
    exception_handlers=exception_handlers
)

broker = KafkaBroker("localhost:29092", middlewares=[exception_middleware])

```

2024-07-30 16:29 UTC, Lancetnik requested changes
Test is too large, can u split it for specific ones?

2024-07-30 16:29 UTC, Lancetnik commented on faststream/broker/middlewares/exception.py
> +    def add_handler(self, exc: Exception) -> Callable[[Exception], None]:
Should return `Callable[[Callable[[Exception], SendableMessage], None]`

2024-08-18 12:10 UTC, sheldygg commented
I made some improvements https://github.com/Rusich90/faststream_fork/pull/1

2024-08-21 19:48 UTC, Lancetnik approved these changes

2024-08-21 19:55 UTC, Lancetnik commented
@kumaranvpl can you, please, check the documentation and merge this one?

2024-08-22 05:21 UTC, kumaranvpl commented
> @kumaranvpl can you, please, check the documentation and merge this one?

Proofread the docs. Will merge it now.

2024-08-22 05:21 UTC, kumaranvpl approved these changes

2024-08-22 05:33 UTC, merged