fix: correct dependency injection of custom context fields implementing partial __eq__/__ne__
airtai/faststream pull request #1809
Opened 2024-09-23 20:55 UTC by antoinehumbert

This PR fixes issue #1806

It includes 2 regression tests related to both corrections in `faststream.utils.context.types` for the 2 use cases where value is compared to EMPTY.

Note that the issue description is incorrect as the custom field class must implement `__ne__` and not only `__eq__` to trigger the problem. This is the reason for the `User` implementation provided in regression test.

Please, let me know if PR needs some improvements.

2024-09-24 04:57 UTC, Lancetnik submitted a review, later dismissed

2024-09-24 04:58 UTC, Lancetnik commented
LGTM, thank you!

2024-09-24 16:21 UTC, Lancetnik commented
> Sorry for not executing the pre-commit check before submitting PR. Do you want me to correct those errors ?

It will be really kind

2024-09-24 17:45 UTC, Lancetnik requested changes

2024-09-24 17:45 UTC, Lancetnik commented on examples/e12_custom_context.py
> +from typing import TYPE_CHECKING, Any
Can you move your example to just a `tests/utils/context/test_main.py` 2 tests? It is too complex to be an example

2024-09-24 20:12 UTC, Lancetnik approved these changes

2024-09-24 20:13 UTC, Lancetnik commented
@antoinehumbert can you run precommit please? 😄

2024-09-24 20:18 UTC, antoinehumbert commented
Will do tomorrow. Sorry for the incontinence.

2024-09-25 05:48 UTC, antoinehumbert commented
Hi! Everything looks good now.

2024-09-25 15:53 UTC, Lancetnik approved these changes

2024-09-25 15:59 UTC, merged