do not assume discriminator is not a property
airtai/faststream pull request #1811
Opened 2024-09-24 10:03 UTC by lecko-cngroup

# Description

We happen to have attribute named `discriminator` in few of our models. This PR prevents `KeyError: 'propertyName'` since the schema generation code incorrectly assumes `discriminator` is keyword used to specify `propertyName`.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (a non-breaking change that resolves an issue)

2024-09-24 17:24 UTC, Lancetnik requested changes
@@lecko-cn group thank you for the PR? Can you please add simple test with your case to `tests/async api` to be sure that this behavior fixed for the future refactoring? Anybody can remove id by accident without tests restriction

2024-09-24 20:25 UTC, Lancetnik commented
Btw, I am planning to make a release tomorrow evening. It will be great to see your fix in it.

2024-09-25 11:53 UTC, lecko-cngroup commented
@Lancetnik I guess these 2 new tests should be enough, right?

2024-09-25 15:48 UTC, Lancetnik approved these changes

2024-09-25 16:01 UTC, merged