New AsyncAPI naming
airtai/faststream pull request #735
Opened 2023-09-25 10:00 UTC by Sternakt

# Description

Rework the asyncapi.py for Kafka and Rabbit brokers to now name the channels by their respective topics.

Fixes #638 

## Type of change

- [x] Bug fix (a non-breaking change that resolves an issue)
- [ ] This change requires a documentation update

## Checklist

- [x] My code adheres to the style guidelines of this project (`scripts/lint.sh` shows no errors)
- [x] I have conducted a self-review of my own code
- [x] I have made the necessary changes to the documentation
- [x] My changes do not generate any new warnings
- [x] I have added tests to validate the effectiveness of my fix or the functionality of my new feature
- [x] Both new and existing unit tests pass successfully on my local environment by running `scripts/test-cov.sh`
- [x] I have ensured that static analysis tests are passing by running `scripts/static-anaylysis.sh`
- [ ] I have included code examples to illustrate the modifications

2023-09-25 10:38 UTC, Lancetnik commented
I can't approve these changes and I am totally disagree with this naming policy.

2023-09-25 10:40 UTC, Lancetnik commented
According AsyncAPI channel name is an operation name, not the subject one. All subject information should contains in bindings. This reason I suggest to name our channels based on the handler functions name.
Adding topic name to it - just a my initiatives, but it conflicts with the original AsyncAPI spec. For now you are totally breaks this logic.

2023-09-25 10:42 UTC, Lancetnik commented
Also, before so breaking changes, we need to fix them in the our specification, write some function -> names examples, conform our view, and then write a code

2023-09-25 10:43 UTC, Lancetnik commented
I think, we need to ask some help from AsyncAPI group to resolve our view

2023-09-25 10:43 UTC, Lancetnik requested changes
We need to represent and approve our view before code writing

2023-09-25 12:09 UTC, davorrunje commented
Let's discuss it all together on Discord when you have time

2023-10-04 16:06 UTC, Lancetnik commented on faststream/kafka/asyncapi.py
> +        print(payloads)
Remove all debug prints. please

2023-10-04 18:40 UTC, Sternakt commented on faststream/kafka/asyncapi.py
> +        print(payloads)
Removed

2023-10-05 05:35 UTC, Lancetnik commented
Btw, can you change Nats naming behavior too and write AsyncAPI tests for it?

2023-10-05 14:29 UTC, Sternakt commented
> Btw, can you change Nats naming behavior too and write AsyncAPI tests for it?

Done :)

2023-10-06 11:43 UTC, Lancetnik commented
@Sternakt looks like `Msg` in payload naming is needless `test_test:Handle:Message:Msg:Payload`

2023-10-06 11:43 UTC, Lancetnik commented
Also, we have no tests on Publisher naming, I'll add it

2023-10-07 19:00 UTC, Lancetnik approved these changes

2023-10-07 19:11 UTC, Lancetnik commented
@Sternakt, @davorrunje, 0.2.3 is ready to merge

2023-10-08 11:44 UTC, davorrunje approved these changes

2023-10-08 11:51 UTC, merged