Implement validate and no_ack subscriber options (#926)
airtai/faststream pull request #988
Opened 2023-11-23 15:31 UTC by mihail8531

# Description

Please include a summary of the change and specify which issue is being addressed. Additionally, provide relevant motivation and context.

Fixes # (issue number)

## Type of change

Please delete options that are not relevant.

- [ ] Documentation (typos, code examples, or any documentation updates)
- [ ] Bug fix (a non-breaking change that resolves an issue)
- [x] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a fix or feature that would disrupt existing functionality)
- [x] This change requires a documentation update

## Checklist

- [x] My code adheres to the style guidelines of this project (`scripts/lint.sh` shows no errors)
- [x] I have conducted a self-review of my own code
- [x] I have made the necessary changes to the documentation
- [x] My changes do not generate any new warnings
- [x] I have added tests to validate the effectiveness of my fix or the functionality of my new feature
- [x] Both new and existing unit tests pass successfully on my local environment by running `scripts/test-cov.sh`
- [x] I have ensured that static analysis tests are passing by running `scripts/static-anaylysis.sh`
- [ ] I have included code examples to illustrate the modifications

2023-11-24 16:57 UTC, Lancetnik requested changes
Thanks for your great job! It is really cool!

But I have a little comments alread. Also, I wish to ask you about brokers' `router.pyi` and `fastapi.pyi` signature changes

2023-11-24 16:57 UTC, Lancetnik commented on faststream/broker/core/abc.py
> +            no_ack: Whether not to ack/nack/reject messages
Docstrings should ends with a dot `.` to be consistent with other docstrings

2023-11-24 16:57 UTC, Lancetnik commented on tests/brokers/kafka/test_consume.py
> +    async def test_consume_validate_false(
Please, move this testcase from final broker case to basic TestCase class: it has no broker-based dependencies, so we can write it at once and need no create a copies

2023-11-24 20:51 UTC, Lancetnik submitted a review, later dismissed

2023-11-24 20:52 UTC, Lancetnik commented
Wait a bit, I need to refactor some logic before it can be merged

2023-11-24 21:03 UTC, Lancetnik approved these changes

2023-11-24 21:06 UTC, Lancetnik requested changes
Can you add these options to broker.__init__ too (apply it to all subscribers by default, by overrides it by subscriber value if it is setted)?

2023-11-28 07:27 UTC, davorrunje commented
@mihail8531 @Lancetnik is not available this week, we are waiting for him to return to merge this PR.

2023-12-01 19:56 UTC, Lancetnik commented
@davorrunje we are ready

2023-12-02 08:04 UTC, davorrunje approved these changes

2023-12-02 08:08 UTC, merged